AllCops:
  SuggestExtensions:
    rubocop-rake: false
require:
  - rubocop-rails
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
convention:Style/FrozenStringLiteralComment:
  Enabled: true
Layout/LineLength:
  Max: 170
ruby:
  config_file: config/rubocop.yml
